# Generated by Django 5.2.8 on 2025-11-24 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('business_license', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=50)),
                ('business_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('sustainability_certificate', models.FileField(blank=True, upload_to='vendor_certificates/')),
                ('verification_documents', models.FileField(blank=True, upload_to='vendor_docs/')),
                ('rating', models.FloatField(default=0.0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eco_impact_score', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='vendor_logos/')),
                ('banner_image', models.ImageField(blank=True, upload_to='vendor_banners/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
